sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t antonkovalenko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antonkovalenko/react-test npm test

after_success:
  - docker build -t akovalenko/multi-client ./client
  - docker build -t akovalenko/multi-nginx ./nginx
  - docker build -t akovalenko/multi-server ./server
  - docker build -t akovalenko/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and put them to docker hub
  - docker push akovalenko/multi-client
  - docker push akovalenko/multi-nginx
  - docker push akovalenko/multi-server
  - docker push akovalenko/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-us-east-1-201886813087"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY